[package]
name = "deno_grpc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "gRPC server implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
